# Generated by Django 4.2.13 on 2024-06-08 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Суть письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временные данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Письмо для админа',
                'verbose_name_plural': 'Письма для админа',
                'ordering': ('-timestamp',),
            },
        ),
    ]
