# Generated by Django 4.2.13 on 2024-07-11 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_title', models.CharField(max_length=30, verbose_name='Название статьи')),
                ('articles_title_img', models.ImageField(upload_to='image/articles_img/', verbose_name='Титульная картинка')),
                ('articles_description', tinymce.models.HTMLField(default='Здесь надо добавить описание статьи для титульной страницы!', verbose_name='Описание статьи')),
                ('articles_text', tinymce.models.HTMLField(default='Здесь надо добавить текст статьи!', verbose_name='Текст статьи')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_category_title', models.CharField(max_length=20, verbose_name='Категория')),
                ('articles_category_img', models.ImageField(upload_to='image/articles_category/', verbose_name='Титульная картинка категории')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ArticlesReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7)),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
        migrations.CreateModel(
            name='ArticlesFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'default_related_name': 'articles_favorites',
            },
        ),
        migrations.CreateModel(
            name='ArticlesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories'),
        ),
        migrations.AddField(
            model_name='articles',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='articles.articlesreactions', verbose_name='Реакции'),
        ),
        migrations.AddConstraint(
            model_name='articlesfavorites',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='Уникальность в избранном'),
        ),
    ]
