# Generated by Django 4.2.13 on 2024-07-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_title', models.CharField(max_length=30, verbose_name='Название статьи')),
                ('articles_title_img', models.ImageField(upload_to='image/articles_img/', verbose_name='Титульная картинка')),
                ('articles_description', models.CharField(default='Описание статьи для титульной страницы!', max_length=50, verbose_name='Описание статьи')),
                ('articles_text_1', tinymce.models.HTMLField(default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 1 (left)')),
                ('article_img_1', models.ImageField(upload_to='image/articles_img/', verbose_name='Картинка 1')),
                ('articles_text_2', tinymce.models.HTMLField(default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 2 (string)')),
                ('articles_text_3', tinymce.models.HTMLField(default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 3 (right)')),
                ('article_img_2', models.ImageField(upload_to='image/articles_img/', verbose_name='Картинка 2')),
                ('articles_text_4', tinymce.models.HTMLField(default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 4 (string)')),
                ('articles_text_5', tinymce.models.HTMLField(default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 5 (left)')),
                ('article_img_3', models.ImageField(upload_to='image/articles_img/', verbose_name='Картинка 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_category_title', models.CharField(max_length=40, verbose_name='Категория')),
                ('articles_category_img', models.ImageField(upload_to='image/articles_category/', verbose_name='Титульная картинка категории')),
                ('articles_category_description', models.CharField(default='Описание категории', max_length=100, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ArticlesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/articles_img/', verbose_name='Карусель картинок')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.articles', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories', verbose_name='Категория'),
        ),
    ]
