# Generated by Django 4.2.13 on 2024-07-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesimage',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='articles.articles', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlesimage',
            name='images',
            field=models.ImageField(upload_to='image/articles_carousel/', verbose_name='Карусель картинок'),
        ),
    ]
