# Generated by Django 4.2.13 on 2024-07-20 19:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articles_text_1',
            field=tinymce.models.HTMLField(default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 1 (left)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_2',
            field=tinymce.models.HTMLField(default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 2 (string)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_3',
            field=tinymce.models.HTMLField(default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 3 (right)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_4',
            field=tinymce.models.HTMLField(default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 4 (string)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_5',
            field=tinymce.models.HTMLField(default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 5 (left)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='articlesimage',
            name='images',
            field=models.ImageField(upload_to='images/articles_img/', verbose_name='Карусель картинок'),
        ),
    ]
