# Generated by Django 4.2.13 on 2024-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescategories',
            name='articles_category_title',
            field=models.CharField(max_length=40, verbose_name='Категория'),
        ),
    ]
