# Generated by Django 4.2.13 on 2024-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlescategories_articles_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategories',
            name='description',
            field=models.CharField(default='Описание категории', max_length=100, verbose_name='Описание'),
        ),
    ]
