# Generated by Django 4.2.13 on 2024-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlesimage_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/articles_img/', verbose_name='Картинка 1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/articles_img/', verbose_name='Картинка 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/articles_img/', verbose_name='Картинка 3'),
        ),
        migrations.AlterField(
            model_name='articlesimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='image/articles_carousel/', verbose_name='Карусель картинок'),
        ),
    ]
