# Generated by Django 4.2.13 on 2024-07-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlescategories_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescategories',
            old_name='description',
            new_name='articles_category_description',
        ),
    ]
