# Generated by Django 4.2.13 on 2024-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_description_articlescategories_articles_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
