# Generated by Django 4.2.13 on 2024-07-28 09:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_articles_article_img_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articles_text_1',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', null=True, verbose_name='Текст статьи 1 (left)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_2',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', null=True, verbose_name='Текст статьи 2 (string)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_3',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', null=True, verbose_name='Текст статьи 3 (right)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_4',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', null=True, verbose_name='Текст статьи 4 (string)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text_5',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', null=True, verbose_name='Текст статьи 5 (left)'),
        ),
    ]
