# Generated by Django 4.2.13 on 2024-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlescategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(default='lll', unique=True),
        ),
    ]
