# Generated by Django 4.2.14 on 2024-07-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articles_article_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_img_2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='articles_text_2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='articles_text_3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='articles_text_4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='articles_text_5',
        ),
    ]
