# Generated by Django 4.2.13 on 2024-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
