# Generated by Django 4.2.14 on 2024-08-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articles_article_img_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
