# Generated by Django 4.2.14 on 2024-08-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlescategories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescategories',
            name='slug',
        ),
    ]
