# Generated by Django 4.2.14 on 2024-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_articles_article_img_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img_1',
            field=models.ImageField(null=True, upload_to='image/articles_detail_img/', verbose_name='Картинка 1'),
        ),
    ]
