# Generated by Django 4.2.14 on 2024-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articles_article_img_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img_1',
            field=models.ImageField(default='Server error', upload_to='image/articles_detail_img/', verbose_name='Картинка 1'),
        ),
    ]
