# Generated by Django 4.2.13 on 2024-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_articlescategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articles_description',
            field=models.TextField(default='Здесь надо добавить описание статьи для титульной страницы!', verbose_name='Описание статьи'),
        ),
    ]
