# Generated by Django 4.2.14 on 2024-07-30 12:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_articles_article_img_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/articles_description_img/', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='articles',
            name='articles_text_2',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 2 (string)'),
        ),
        migrations.AddField(
            model_name='articles',
            name='articles_text_3',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 3 (right)'),
        ),
        migrations.AddField(
            model_name='articles',
            name='articles_text_4',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. Строка. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 4 (string)'),
        ),
        migrations.AddField(
            model_name='articles',
            name='articles_text_5',
            field=tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Текст статьи 5 (left)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/articles_description_img/', verbose_name='Картинка 1'),
        ),
    ]
