# Generated by Django 4.2.13 on 2024-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_articles_articles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articles_description',
            field=models.CharField(default='Описание статьи для титульной страницы!', max_length=50, verbose_name='Описание статьи'),
        ),
    ]
