# Generated by Django 4.2.14 on 2024-09-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_articles_article_img_2_articles_articles_text_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesSubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_subcategory_title', models.CharField(max_length=40, verbose_name='Подкатегория')),
                ('articles_subcategory_img', models.ImageField(upload_to='image/articles_category/', verbose_name='Титульная картинка подкатегории')),
                ('articles_subcategory_description', models.CharField(default='Описание подкатегории', max_length=100, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(verbose_name='Опубликовать')),
                ('category', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlessubcategories', verbose_name='Подкатегория'),
        ),
    ]
