# Generated by Django 4.2.13 on 2024-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_articles_articles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articles_text',
            field=models.TextField(default='Здесь надо добавить текст статьи!', verbose_name='Текст статьи'),
        ),
    ]
