# Generated by Django 4.2.13 on 2024-07-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_articles_articles_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='update',
        ),
    ]
