# Generated by Django 4.2.13 on 2024-07-14 19:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_articles_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articles_text',
            field=tinymce.models.HTMLField(default='Здесь надо добавить текст статьи!', verbose_name='Текст статьи'),
        ),
    ]
