version: '3.8'

services:
  web:
    image: python:3.9
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - STATIC_URL=/static/
      - STATICFILES_DIRS=/app/static
      - MEDIA_URL=/media/
      - MEDIA_ROOT=/app/media
    depends_on:
      - db

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: