# Generated by Django 4.2.14 on 2024-08-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieves_title', models.CharField(max_length=50, verbose_name='Название')),
                ('achieves_img', models.ImageField(upload_to='image/achieves/', verbose_name='Картинка достижения')),
                ('achieves_description', models.CharField(max_length=150, verbose_name='Описание достижения')),
                ('achieves_filter', models.CharField(max_length=50, verbose_name='Фильтр')),
                ('created_at', models.DateTimeField(verbose_name='Создано')),
                ('is_published', models.BooleanField(verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-created_at'],
            },
        ),
    ]
