# Generated by Django 4.2.14 on 2024-08-03 20:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCuteAngel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_day', models.CharField(max_length=40, verbose_name='Название дня')),
                ('day_description', tinymce.models.HTMLField(blank=True, default='Текст статьи. 1 отступ. 100-130 слов. Шрифт: заголовки - 18, подзаголовки - 14, текст - 12, белый цвет.', verbose_name='Описание дня')),
                ('period', models.CharField(max_length=30, verbose_name='Приод отношений')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Ангел',
                'verbose_name_plural': 'Ангел',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AngelsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='img/angels_carousel/', verbose_name='Карусель картинок')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='cute.mycuteangel', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
