# Generated by Django 4.2.14 on 2024-08-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cute', '0002_alter_mycuteangel_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngelsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='img/angels_carousel/', verbose_name='Карусель картинок')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='cute.mycuteangel', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
