# Generated by Django 4.2.13 on 2024-06-08 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_category_title', models.CharField(max_length=20, verbose_name='Категория')),
                ('articles_category_img', models.ImageField(upload_to='image/articles_category/', verbose_name='Титульная картинка категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations_title', models.CharField(max_length=30, verbose_name='Название организации')),
                ('organizations_title_img', models.ImageField(upload_to='image/organizations_img/', verbose_name='Титульная картинка')),
                ('organizations_description', tinymce.models.HTMLField(default='Здесь надо добавить описание организации для титульной страницы!', verbose_name='Описание организации')),
                ('organizations_text', tinymce.models.HTMLField(default='Здесь надо добавить текст истории организации!', verbose_name='Текст истории организации')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Myths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myths_title', models.CharField(max_length=30, verbose_name='Название мифа')),
                ('myths_title_img', models.ImageField(upload_to='image/myths_img/', verbose_name='Титульная картинка')),
                ('myths_description', tinymce.models.HTMLField(default='Здесь надо добавить описание мифа для титульной страницы!', verbose_name='Описание мифа')),
                ('myths_text', tinymce.models.HTMLField(default='Здесь надо добавить текст мифа!', verbose_name='Текст мифа')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories')),
            ],
            options={
                'verbose_name': 'Миф',
                'verbose_name_plural': 'Мифы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Miracles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miracles_title', models.CharField(max_length=30, verbose_name='Название чуда')),
                ('miracles_title_img', models.ImageField(upload_to='image/natures_img/', verbose_name='Титульная картинка')),
                ('miracles_description', tinymce.models.HTMLField(default='Здесь надо добавить описание чуда для титульной страницы!', verbose_name='Описание чуда')),
                ('miracles_text', tinymce.models.HTMLField(default='Здесь надо добавить текст чуда!', verbose_name='Текст чуда')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories')),
            ],
            options={
                'verbose_name': 'Чудо',
                'verbose_name_plural': 'Чудеса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Legends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legends_title', models.CharField(max_length=30, verbose_name='Название легенды')),
                ('legends_title_img', models.ImageField(upload_to='image/legends_img/', verbose_name='Титульная картинка')),
                ('legends_description', tinymce.models.HTMLField(default='Здесь надо добавить описание легенды для титульной страницы!', verbose_name='Описание легенды')),
                ('legends_text', tinymce.models.HTMLField(default='Здесь надо добавить текст легенды!', verbose_name='Текст легенды')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories')),
            ],
            options={
                'verbose_name': 'Легенда',
                'verbose_name_plural': 'Легенды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_title', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('fashion_title_img', models.ImageField(upload_to='image/fashion_img/', verbose_name='Титульная картинка')),
                ('fashion_description', tinymce.models.HTMLField(default='Здесь надо добавить описание стиля моды для титульной страницы!', verbose_name='Описание стиля моды')),
                ('fashion_text', tinymce.models.HTMLField(default='Здесь надо добавить текст истории моды!', verbose_name='Текст истории моды')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories')),
            ],
            options={
                'verbose_name': 'Мода',
                'verbose_name_plural': 'Мода',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brends_title', models.CharField(max_length=30, verbose_name='Название бренда')),
                ('brends_title_img', models.ImageField(upload_to='image/brends_img/', verbose_name='Титульная картинка')),
                ('brends_description', tinymce.models.HTMLField(default='Здесь надо добавить описание бренда для титульной страницы!', verbose_name='Описание бренда')),
                ('brends_text', tinymce.models.HTMLField(default='Здесь надо добавить текст истории бренда!', verbose_name='Текст истории бренда')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['-created_at'],
            },
        ),
    ]
