# Generated by Django 4.2.13 on 2024-06-08 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_title', models.CharField(max_length=30, verbose_name='Название статьи')),
                ('articles_title_img', models.ImageField(upload_to='image/articles_img/', verbose_name='Титульная картинка')),
                ('articles_description', tinymce.models.HTMLField(default='Здесь надо добавить описание статьи для титульной страницы!', verbose_name='Описание статьи')),
                ('articles_text', tinymce.models.HTMLField(default='Здесь надо добавить текст статьи!', verbose_name='Текст статьи')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='legends',
            name='author',
        ),
        migrations.RemoveField(
            model_name='legends',
            name='category',
        ),
        migrations.RemoveField(
            model_name='miracles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='miracles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='myths',
            name='author',
        ),
        migrations.RemoveField(
            model_name='myths',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='author',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='category',
        ),
        migrations.AlterField(
            model_name='articlescategories',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='Brends',
        ),
        migrations.DeleteModel(
            name='Fashion',
        ),
        migrations.DeleteModel(
            name='Legends',
        ),
        migrations.DeleteModel(
            name='Miracles',
        ),
        migrations.DeleteModel(
            name='Myths',
        ),
        migrations.DeleteModel(
            name='Organizations',
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescategories'),
        ),
    ]
