# Generated by Django 4.2.13 on 2024-06-08 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_articles_articlescomment_remove_fashion_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7)),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
        migrations.CreateModel(
            name='ArticlesFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'default_related_name': 'articles_favorites',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlesreactions', verbose_name='Реакции'),
        ),
        migrations.AddConstraint(
            model_name='articlesfavorites',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='Уникальность в избранном'),
        ),
    ]
