# Generated by Django 4.2.13 on 2024-06-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlesreactions_articlesfavorites_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescomment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
