# Generated by Django 4.2.13 on 2024-06-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_textscategoriestags_textsgenres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textsgenres',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='textsgenres',
            name='texts_tag',
            field=models.CharField(max_length=200, unique=True, verbose_name='Жанр'),
        ),
    ]
