# Generated by Django 4.2.13 on 2024-06-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_alter_favorites_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reactions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='user',
        ),
    ]
