# Generated by Django 4.2.13 on 2024-06-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texts', '0005_alter_reactions_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='reaction',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000, verbose_name='Текст Комментария')),
                ('is_published', models.BooleanField(verbose_name='Отправить')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
        migrations.AddField(
            model_name='texts',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='texts.comments', verbose_name='Комментарий'),
        ),
    ]
