# Generated by Django 4.2.13 on 2024-06-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0007_comment_remove_texts_comment_delete_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'default_related_name': 'texts_favorites', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
