# Generated by Django 4.2.13 on 2024-06-08 16:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextsCategoriesTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_title', models.CharField(max_length=20, verbose_name='Категория')),
                ('publication', models.BooleanField(verbose_name='Опубликовать')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет в НЕХ')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TextsGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts_tag', models.CharField(max_length=200, unique=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг Жанра',
                'verbose_name_plural': 'Тэги Жанров',
            },
        ),
        migrations.AlterField(
            model_name='texts',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='texts.textscategoriestags', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='texts.textsgenres', verbose_name='Жанр'),
        ),
        migrations.DeleteModel(
            name='TextsCategories',
        ),
        migrations.DeleteModel(
            name='TextsGenresTags',
        ),
    ]
