# Generated by Django 4.2.13 on 2024-06-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texts', '0003_alter_textsgenres_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'default_related_name': 'favorites', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RenameField(
            model_name='textsgenres',
            old_name='texts_tag',
            new_name='texts_genre',
        ),
        migrations.AlterUniqueTogether(
            name='reactions',
            unique_together={('user',)},
        ),
        migrations.AddField(
            model_name='texts',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='texts.reactions', verbose_name='Реакции'),
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='content_object',
        ),
    ]
